### PR TITLE
ncar-ngeet compatible release of sci-1.3.0 api-1.0.0

### PR DESCRIPTION
**Pull request by rgknox**
The head of NCAR/fates-release (which had a flat-non history, for reasons still unknown) was merged into the most similar commit hash, and resolved and then merged up to tag sci-1.3.0 api-1.0.0.  This allows a unified history that both NCAR and NGEET can use for public releases.

Code review: performed initial merge and conflict resolution with @ckoven.  

Test suite: cheyenne, intel (ed, aux_clm45),  baseline was added from tag  sci.1.3.0_api.1.0.0

Test namelist changes: this release is still API 1.0.0
Test answer changes: yes, 2 science changes since last release
Test summary: cheyenne(intel): 

ed: all PASS B4B with  tag  sci.1.3.0_api.1.0.0
aux_clm45: all PASS B4B with exceptions, base and head both had following fails:

From Base:
```
  FAIL ERP_D_Ld5.f09_g16.ICLM45VIC.cheyenne_intel.clm-vrtlay_interp RUN time=151
  FAIL ERP_Lm54_Mmpi-serial.1x1_numaIA.ICLM45BGCCROP.cheyenne_intel.clm-cropMonthOutput MEMLEAK memleak detected, memory went from 207.520000 to 254.470000 in 20128 days
  FAIL ERP_Ly20_Mmpi-serial.1x1_numaIA.ICLM45BGCDVCROP.cheyenne_intel.clm-cropMonthOutput MEMLEAK memleak detected, memory went from 209.230000 to 234.650000 in 81129 days
  FAIL ERP_P15x2_Lm25.f10_f10.ICLM45BGCDVCROP.cheyenne_intel.clm-monthly MEMLEAK memleak detected, memory went from 206.090000 to 234.230000 in 9929 days
  FAIL ERP_P15x2_Lm36.f10_f10.ICLM45BGCCROP.cheyenne_intel.clm-irrig_o3_reduceOutput MEMLEAK memleak detected, memory went from 199.500000 to 223.480000 in 10429 days
  FAIL ERS_D_Ld3.f09_g16_gl4.IG1850CRUCLM50BGCCROP.cheyenne_intel.clm-clm50KitchenSink RUN time=65
  FAIL ERS_D_Ld3.f19_g16_gl4.IG1850CRUCLM50BGCCROP.cheyenne_intel.clm-clm50dynroots RUN time=74
  FAIL ERS_D_Ld7_Mmpi-serial.1x1_smallvilleIA.IHISTCLM50BGCCROP.cheyenne_intel.clm-decStart1851_noinitial RUN time=41
  FAIL SMS_Lm1_D.f10_f10.ICLM45BGCCROP.cheyenne_intel.clm-snowlayers_3_monthly RUN time=51
```

test(head) details:
```
cheyenne6 clmed-tests/aux_clm45.cheyenne.intel.C2760c05-Fe0249ae> ./cs.status.20170914_185614_me2h41 | grep FAIL
  FAIL ERP_D_Ld5.f09_g16.ICLM45VIC.cheyenne_intel.clm-vrtlay_interp RUN time=150
  FAIL ERP_Ld5.f10_f10.I1850CLM45BGC.cheyenne_intel.rtm-rtmOff RUN time=43251
  FAIL ERP_Lm54_Mmpi-serial.1x1_numaIA.ICLM45BGCCROP.cheyenne_intel.clm-cropMonthOutput MEMLEAK memleak detected, memory went from 207.550000 to 254.500000 in 20128 days
  FAIL ERP_Ly20_Mmpi-serial.1x1_numaIA.ICLM45BGCDVCROP.cheyenne_intel.clm-cropMonthOutput MEMLEAK memleak detected, memory went from 209.250000 to 234.680000 in 81129 days
  FAIL ERP_P15x2_Lm25.f10_f10.ICLM45BGCDVCROP.cheyenne_intel.clm-monthly MEMLEAK memleak detected, memory went from 206.010000 to 234.010000 in 9929 days
  FAIL ERP_P15x2_Lm36.f10_f10.ICLM45BGCCROP.cheyenne_intel.clm-irrig_o3_reduceOutput MEMLEAK memleak detected, memory went from 199.240000 to 223.020000 in 10429 days
  FAIL ERS_D_Ld3.f09_g16_gl4.IG1850CRUCLM50BGCCROP.cheyenne_intel.clm-clm50KitchenSink RUN time=65
  FAIL ERS_D_Ld3.f19_g16_gl4.IG1850CRUCLM50BGCCROP.cheyenne_intel.clm-clm50dynroots RUN time=75
  FAIL ERS_D_Ld7_Mmpi-serial.1x1_smallvilleIA.IHISTCLM50BGCCROP.cheyenne_intel.clm-decStart1851_noinitial RUN time=41
  FAIL SMS_Lm1_D.f10_f10.ICLM45BGCCROP.cheyenne_intel.clm-snowlayers_3_monthly RUN time=51
```

### CODE REVIEW

**Comment by rgknox** [comment]
One test failed in the merge that did not fail in the baseline.

Apparently  ERP_Ld5.f10_f10.I1850CLM45BGC.cheyenne_intel.rtm-rtmOff exceeded its walltime limit.

```
Finished creating component namelists
-------------------------------------------------------------------------
 - Prestage required restarts into /glade/scratch/rgknox/ERP_Ld5.f10_f10.I1850CLM45BGC.cheyenne_intel.rtm-rtmOff.GC.20170914_185614_me2h41/run
 - Case input data directory (DIN_LOC_ROOT) is /glade/p/cesmdata/cseg/inputdata 
 - Checking for required input datasets in DIN_LOC_ROOT
-------------------------------------------------------------------------
```

**Comment by ekluzek** [comment]
Hi @rgknox. So there are some things I'd like to have you do with your testing. The mpi-serial tests fail on ys/ch, and you have to run them separately. I create a list for the mpi-serial tests that fail and use the "-f" option to create_test. That will help narrow down the list of more important fails. Also we usually ignore the MEMFAIL and the shorter MEMLEAK tests.

So to get the list of the important fails, run through the parse_cime.cs.status script with the "-s" option. From your cime directory where your cases are (cime/script as default which is what I do), run it like this...

../../parse_cime.cs.status -s cs.status*

Make sure you are just using the right list of cs.status files in above.



I was thinking about rerunning this all on my own, but I'm not going to have time to do that. And I think we need to teach about these glitches that we have...

It would be good to rerun the test that failed because of walltime limit (three hours of wallclock should be enough). How much wallclock was it given? The default is 12, so it shouldn't have died because of that much.

**Comment by rgknox** [comment]
@ekluzek, here is the output from the parse script:
```
cheyenne4 clmed-tests/aux_clm45.cheyenne.intel.C2760c05-Fe0249ae> ~/SyncLocal/fates-clm/parse_cime.cs.status -s cs.status.20170914_185614_me2h41 
================================================================================
Test summary
92 Total tests
0 Tests pending
86 Tests passed
0 Tests compare different to baseline
6 Tests failed
================================================================================
================================================================================
These tests passed
================================================================================
ERI_D_Ld9.T31_g37.ICLM45.cheyenne_intel.clm-SNICARFRC
ERI_D_Ld9.f09_g16.ICLM45BGC.cheyenne_intel.clm-default
ERI_D_Ld9.f10_f10.ICLM45BGC.cheyenne_intel.clm-default
ERI_D_Ld9.f10_f10.ICLM45BGC.cheyenne_intel.clm-reduceOutput
ERI_D_Ld9.f10_f10.ICRUCLM50BGC.cheyenne_intel.clm-default
ERI_D_Ld9.ne30_g16.ICLM45BGC.cheyenne_intel.clm-vrtlay
ERI_Ld9.f09_g16.ICLM45BGC.cheyenne_intel.clm-cn_conly
ERI_Ld9.f10_f10.ICLM45BGC.cheyenne_intel.clm-drydepnomegan
ERI_Ld9.f10_f10.ICRUCLM50BGC.cheyenne_intel.clm-reduceOutput
ERI_Ld9.f45_g37.ICRUCLM50BGC.cheyenne_intel.clm-nofire
ERI_N2_Ld9.f19_g16.ICRUCLM45BGCCROP.cheyenne_intel.clm-default
ERP_D_Ld3_P15x2.f10_f10.ICLM45BGC.cheyenne_intel.clm-default
ERP_D_Ld5.f10_f10.I1850CLM45BGC.cheyenne_intel.rtm-default
ERP_D_Ld5.f10_f10.ICLM45.cheyenne_intel.clm-decStart
ERP_D_Ld5.f10_f10.ICLM45BGC.cheyenne_intel.clm-NoVSNoNI
ERP_D_Ld5.f10_f10.ICLM45BGC.cheyenne_intel.clm-rootlit
ERP_D_Ld5.f10_f10.ICLM45BGCCROP.cheyenne_intel.clm-allActive
ERP_D_Ld5.f10_f10.ICLM45VIC.cheyenne_intel.clm-vrtlay
ERP_D_Ld5.f19_g16.ICLM45BGC.cheyenne_intel.clm-default
ERP_D_Ld5.f19_g16.ICRUCLM50BGC.cheyenne_intel.clm-default
ERP_D_Ld5.f19_g16.ICRUCLM50BGC.cheyenne_intel.clm-fire_emis
ERP_D_Ld5.f19_g16_gl4.IGCLM45BGC.cheyenne_intel.clm-glcMEC_changeFlags
ERP_D_P15x2.f10_f10.IHISTCLM50BGC.cheyenne_intel.clm-ciso_decStart
ERP_D_P15x2_Ld3.f10_f10.ICRUCLM50BGC.cheyenne_intel.clm-default
ERP_D_P15x2_Ld3.f10_f10.ICRUCLM50BGC.cheyenne_intel.clm-flexCN_FUN
ERP_D_P15x2_Ld3.f10_f10.ICRUCLM50BGC.cheyenne_intel.clm-luna
ERP_D_P15x2_Ld3.f10_f10.ICRUCLM50BGC.cheyenne_intel.clm-noFUN_flexCN
ERP_D_P15x2_Ld3.f10_f10.ICRUCLM50BGCCROP.cheyenne_intel.clm-cropColdStart
ERP_D_P15x2_Ld30.f10_f10.ICRUCLM50BGC.cheyenne_intel.clm-default
ERP_D_P15x2_Ld5.f10_f10.ICRUCLM50BGCCROP.cheyenne_intel.clm-irrig_spunup
ERP_Ld5.f10_f10.I1850CLM45BGC.cheyenne_intel.clm-drydepnomegan
ERP_Ld5.f10_f10.I1850CLM45BGC.cheyenne_intel.rtm-rtmOnFloodOnEffvelOn
ERP_Ld5.f10_f10.I1850CLM45BGC.cheyenne_intel.rtm-rtmOnIceOff
ERP_Ld5.f19_g16.I1850CLM45BGC.cheyenne_intel.clm-default
ERP_Ld5.f19_g16.ICLM45BGC.cheyenne_intel.clm-default
ERP_Ld5.f19_g16.ICRUCLM50BGC.cheyenne_intel.clm-default
ERP_Lm54_Mmpi-serial.1x1_numaIA.ICLM45BGCCROP.cheyenne_intel.clm-cropMonthOutput
ERP_Ly20_Mmpi-serial.1x1_numaIA.ICLM45BGCDVCROP.cheyenne_intel.clm-cropMonthOutput
ERP_Ly5.f10_f10.ICLM45BGCCROP.cheyenne_intel.clm-irrig_o3_reduceOutput
ERP_P15x2_Lm13.f10_f10.IHISTCLM50BGC.cheyenne_intel.clm-monthly
ERP_P15x2_Lm25.f10_f10.ICLM45BGCDVCROP.cheyenne_intel.clm-monthly
ERP_P15x2_Lm25.f10_f10.ICLM50BGCDVCROP.cheyenne_intel.clm-monthly
ERP_P15x2_Lm36.f10_f10.ICLM45BGCCROP.cheyenne_intel.clm-irrig_o3_reduceOutput
ERP_P180x2_D_Ld5.f19_g16.I1850CLM45.cheyenne_intel.clm-default
ERP_P60x2_Lm36.f10_f10.ICRUCLM50BGCCROP.cheyenne_intel.clm-clm50cropIrrigMonth_interp
ERS_D_Ld10.T31_g37_gl4.IGHISTCLM50.cheyenne_intel.clm-glcMEC_decrease
ERS_D_Ld12.T31_g37_gl4.IG1850CRUCLM50BGC.cheyenne_intel.clm-glcMEC_spunup_inc_dec_bgc
ERS_D_Ld3.f10_f10.ICLM45BGC.cheyenne_intel.clm-default
ERS_D_Ld3.f10_f10.ICRUCLM50BGC.cheyenne_intel.clm-deepsoil_bedrock
ERS_D_Ld3.f10_f10.ICRUCLM50BGC.cheyenne_intel.clm-default
ERS_D_Ld5.5x5_amazon.ICLM45ED.cheyenne_intel.clm-edTest
ERS_D_Ld5.f09_g16.ICLM45ED.cheyenne_intel.clm-edTest
ERS_D_Ld5.f10_f10.ICLM45ED.cheyenne_intel.clm-edTest
ERS_D_Ld5.f10_f10.IMCRUCLM50BGC.cheyenne_intel.clm-default
ERS_D_Mmpi-serial_Ld5.1x1_brazil.ICLM45ED.cheyenne_intel.clm-edTest
ERS_Ld5_Mmpi-serial.1x1_vancouverCAN.I1PTCLM45.cheyenne_intel.clm-default
ERS_Ld5_Mmpi-serial.1x1_vancouverCAN.I1PTCLM50.cheyenne_intel.clm-default
ERS_Ly3.f10_f10.I1850CRUCLM50BGCCROP.cheyenne_intel.clm-clm50KSinkMOut
ERS_Ly5_P60x1.f10_f10.IHISTCLM50BGCCROP.cheyenne_intel.clm-cropMonthOutput
LII_D_Ld3.f19_g16_gl4.IG1850CLM45.cheyenne_intel.clm-glcMEC_spunup_1way
NCK_Ld1.f10_f10.ICRUCLM45.cheyenne_intel.clm-default
PEM_D_Ld5.ne30_g16.ICLM45BGC.cheyenne_intel.clm-default
PEM_Lm25.f10_f10.ICLM45BGCCROP.cheyenne_intel.clm-cropMonthOutput
SMS_D_Ld1_Mmpi-serial.1x1_mexicocityMEX.ICLM45.cheyenne_intel.clm-default
SMS_D_Ld1_Mmpi-serial.f45_f45.ICLM45.cheyenne_intel.clm-ptsRLA
SMS_D_Ld3.f10_f10.ICLM45BGC.cheyenne_intel.clm-default
SMS_D_Ld3.f10_f10.ICRUCLM50BGC.cheyenne_intel.clm-default
SMS_D_Ld5.f10_f10.ICLM45ED.cheyenne_intel.clm-edTest
SMS_D_Ld5.f45_f45.ICLM45ED.cheyenne_intel.clm-edTest
SMS_D_Ld5_Mmpi-serial.1x1_mexicocityMEX.I1PTCLM50.cheyenne_intel.clm-default
SMS_D_Lm6.f45_f45.ICLM45ED.cheyenne_intel.clm-edTest
SMS_D_Ly2.1x1_brazil.IHISTCLM50BGC.cheyenne_intel.clm-ciso_bombspike1963
SMS_D_Mmpi-serial_Ld5.5x5_amazon.ICLM45ED.cheyenne_intel.clm-edTest
SMS_Ld1.f09_g16.ICRUCLM45.cheyenne_intel.clm-af_bias_v5
SMS_Ld1.f19_g16.ICLM45VIC.cheyenne_intel.clm-default
SMS_Ld1_Mmpi-serial.1x1_mexicocityMEX.I1PTCLM45.cheyenne_intel.clm-default
SMS_Ld1_Mmpi-serial.f45_f45.ICLM45.cheyenne_intel.clm-ptsRLA
SMS_Ld5.f10_f10.ICLM45ED.cheyenne_intel.clm-edTest
SMS_Ld5.f19_g16.ICLM45ED.cheyenne_intel.clm-edTest
SMS_Ld5.f19_g16.IRCP45CLM45BGC.cheyenne_intel.clm-decStart
SMS_Lm1.f09_g16_gl4.IG1850CRUCLM50BGC.cheyenne_intel.clm-clm50KitchenSink
SMS_Lm1.f19_g16_gl4.IG1850CRUCLM50BGC.cheyenne_intel.clm-clm50dynroots
SMS_Lm37.T31_g37_gl4.IG1850CLM50.cheyenne_intel.clm-glcMEC_long
SMS_Ly3_Mmpi-serial.1x1_numaIA.ICRUCLM50BGCCROP.cheyenne_intel.clm-clm50dynroots
SMS_Ly5_Mmpi-serial.1x1_tropicAtl.IHISTCLM50BGC.cheyenne_intel.clm-tropicAtl_subsetMid
SSP_D_Ld10.f19_g16.I1850CLM45BGC.cheyenne_intel.clm-rtmColdSSP
================================================================================
These tests failed
================================================================================
ERP_D_Ld5.f09_g16.ICLM45VIC.cheyenne_intel.clm-vrtlay_interp
ERP_Ld5.f10_f10.I1850CLM45BGC.cheyenne_intel.rtm-rtmOff
ERS_D_Ld3.f09_g16_gl4.IG1850CRUCLM50BGCCROP.cheyenne_intel.clm-clm50KitchenSink
ERS_D_Ld3.f19_g16_gl4.IG1850CRUCLM50BGCCROP.cheyenne_intel.clm-clm50dynroots
ERS_D_Ld7_Mmpi-serial.1x1_smallvilleIA.IHISTCLM50BGCCROP.cheyenne_intel.clm-decStart1851_noinitial
SMS_Lm1_D.f10_f10.ICLM45BGCCROP.cheyenne_intel.clm-snowlayers_3_monthly
```

**Comment by rgknox** [comment]
Something strange happened on the ERP_Ld5.f10_f10.I1850CLM45BGC.cheyenne_intel.rtm-rtmOff
simulation, it must had hung up:

PBS: job killed: walltime 43252 exceeded limit 43200

That is 12 hours of walltime.

**Comment by rgknox** [comment]
@ekluzek , I re-ran ERP_Ld5.f10_f10.I1850CLM45BGC.cheyenne_intel.rtm-rtmOff and it passed all tests.  Not sure what happened the first time.

**Comment by ekluzek** [comment]
OK, this looks good, the tests that fail are due to bug 2441, or expected, or worked on resubmit. I assume the ERP test that worked on resubmit, just glitched out due to a system problem.

**Pull request merged**
